### ISSUE TITLE
New version of Moodle 4.2.<highest> with OneDrive core hack

### ISSUE THREAD

**Issue by mcardle** [praxisdigital/moodle#10]
Re-do the OneDrive core hack from previously (see commits).

Should be a one-liner

**Comment by sampraxis** [comment]
@Mikkeljeppesen1 
Ready to be release.


Branch: [MOODLE_402_STABLE_ONEDRIVE_FIX](https://github.com/praxisdigital/moodle/tree/MOODLE_402_STABLE_ONEDRIVE_FIX)
Tag: [v4.2.3-repository_onedrive-fix](https://github.com/praxisdigital/moodle/tree/v4.2.3-repository_onedrive-fix)

**Comment by Mikkeljeppesen1** [comment]
thx
