### ISSUE TITLE
New version of EF Itai Core Hack

### ISSUE THREAD

**Issue by mcardle** [praxisdigital/moodle#11]
Ef itai runs currently on moodle 3.10 and getting upgraded now. But they have a corehack. 

https://github.com/praxisdigital/moodle/tree/MOODLE_310_STABLE_EF_ITAI_DK_FIX

Cant remember what the corehacks does, maybe ask Tue og Ulrik

**Comment by mcardle** [comment]
Use the newest version of Moodle 4.2

**Comment by sampraxis** [comment]
@Mikkeljeppesen1 

Ready for release

Branch: MOODLE_402_STABLE_EF_ITAI_DK_FIX

**Comment by sampraxis** [comment]
@Mikkeljeppesen1 

Ready for release
Branch: MOODLE_402_STABLE_EF_ITAI_DK_FIX
