### ISSUE TITLE
Create new version of Moodle 4.2.4 with core hack

### ISSUE THREAD

**Issue by mcardle** [praxisdigital/moodle#13]
We need to create a new Moodle version for Moodle 4.2.4 and remove all code from mod_label in the upgrade.php file between the lines:

```
if ($oldversion < 2022112801) {
...
}
``` 

Moodle have changed the way label's are named. So they've added an upgrade script to update to the new naming standard.

The if block does nothing besides updating the name.

**Comment by frederikmillingpytlick** [comment]
**Moodle 4.2.5 branch without mod_label upgrade script:**
https://github.com/praxisdigital/moodle/tree/MOODLE_4.2.5_STABLE_REMOVE_MOD_LABEL_UPGRADE_SCRIPT
