### ISSUE TITLE
Moodle 4.1 with Corehacks for KS

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/moodle#6]
Make a Moodle 4.1 verion with the KS corehaks and correct the code where nessesary to make the Moodle load.

**Comment by frederikmillingpytlick** [comment]
Moodle 4.1.3 branch with KS core hacks: 
https://github.com/praxisdigital/moodle/tree/MOODLE_413_STABLE_KS_CORE_HACKS

**Comment by frederikmillingpytlick** [comment]
Setup Moodle 4.1.3 branch site.

Issues:
- local_org
  - Major:
    - Municipality selector does not work
- theme_kslaring
  - Minor:
    - Should not redirect to fill in the user profile field "municipality", when it has not yet been setup on the site. I was able to add the user profile field by adding &theme=boost in the url. So seems to be the ks theme, that redirects.
- local_catalogue
  - Major:
    - solr engine is not installed in our production environment, but is used by this plugin. The catalogue does not work


Time taken:
- 04/05/2023
  - 1 hour

**Comment by frederikmillingpytlick** [comment]
Awaiting further talk with KS

**Comment by mcardle** [comment]
KS has reached out and are currently reviewing if they should continue on their platform or start fresh - waiting.
