### ISSUE TITLE
Create new Moodle 4.0.8 with moxis core hacks

### ISSUE THREAD

**Issue by mcardle** [praxisdigital/moodle#7]

**Comment by frederikmillingpytlick** [comment]
New branch: [MOODLE_408_STABLE_INCL_MOXIS_FIXES](https://github.com/praxisdigital/moodle/tree/MOODLE_408_STABLE_INCL_MOXIS_FIXES)

**Comment by superfoght** [comment]
@frederikmillingpytlick @Mikkeljeppesen1 
It needs to be updated on studie.smartlearning.dk at least. They experience problems with the calendar.
