### ISSUE TITLE
Fix for core bug https://tracker.moodle.org/browse/MDL-74248

### ISSUE THREAD

**Issue by TubsDK** [praxisdigital/moodle#8]
We need to get the issue moving in the tracker:

https://tracker.moodle.org/browse/MDL-74248

**Comment by frederikmillingpytlick** [comment]
Time spent: 1 hour

**Comment by frederikmillingpytlick** [comment]
Tobias Garske seems to have approved this, awaiting merge

**Comment by frederikmillingpytlick** [comment]
I've asked Tobias Garske to send it further up/down the chain

**Comment by frederikmillingpytlick** [comment]
This fix has been implemented in 4.1.7, 4.2.4, 4.3.1
